2016-03-05 17:05:51 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /Blog/blog/
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 17:15:14 Error: [MissingActionException] Action BlogController::index() could not be found.
Exception Attributes: array (
  'controller' => 'BlogController',
  'action' => 'index',
)
Request URL: /Blog/blog
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BlogController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 17:16:17 Error: [MissingActionException] Action BlogController::index() could not be found.
Exception Attributes: array (
  'controller' => 'BlogController',
  'action' => 'index',
)
Request URL: /Blog/blog
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BlogController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 17:19:33 Error: [MissingActionException] Action BlogController::index() could not be found.
Exception Attributes: array (
  'controller' => 'BlogController',
  'action' => 'index',
)
Request URL: /Blog/blog
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BlogController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 17:33:04 Error: [MissingControllerException] Controller class XController could not be found.
Exception Attributes: array (
  'class' => 'XController',
  'plugin' => NULL,
)
Request URL: /Blog/x
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 17:33:14 Error: [MissingActionException] Action PostsController::index() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'index',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 17:33:49 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:33:51 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:34:26 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:34:32 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:34:45 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:34:51 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:34:53 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 17:36:55 Error: [MissingControllerException] Controller class PostController could not be found.
Exception Attributes: array (
  'class' => 'PostController',
  'plugin' => NULL,
)
Request URL: /Blog/post
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 17:55:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 12]
2016-03-05 17:55:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 17:55:36 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 12]
2016-03-05 17:55:36 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 17:55:43 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 19]
2016-03-05 17:55:43 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Posts/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 19:26:46 Error: [MissingControllerException] Controller class DeleteController could not be found.
Exception Attributes: array (
  'class' => 'DeleteController',
  'plugin' => NULL,
)
Request URL: /Blog/delete
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 19:26:56 Error: [MissingControllerException] Controller class DeleteController could not be found.
Exception Attributes: array (
  'class' => 'DeleteController',
  'plugin' => NULL,
)
Request URL: /Blog/delete
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 19:37:45 Error: [MissingViewException] View file "Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\view.ctp',
)
Request URL: /Blog/Posts/view/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 19:37:50 Error: [MissingViewException] View file "Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\view.ctp',
)
Request URL: /Blog/Posts/view/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 19:38:20 Error: [MissingViewException] View file "Posts\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\view.ctp',
)
Request URL: /Blog/Posts/view/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 19:42:17 Error: [MissingViewException] View file "Posts\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts\\index.ctp',
)
Request URL: /Blog/Posts
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 20:07:12 Error: [MissingControllerException] Controller class AddController could not be found.
Exception Attributes: array (
  'class' => 'AddController',
  'plugin' => NULL,
)
Request URL: /Blog/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 20:24:40 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /Blog/posts/delete/8
Stack Trace:
#0 [internal function]: PostsController->delete('8')
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 20:25:18 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 64]
2016-03-05 20:25:18 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /Blog/posts/delete/8
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 64)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 64, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 64, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 20:25:26 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /Blog/posts/delete/8
Stack Trace:
#0 [internal function]: PostsController->delete('8')
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 20:26:45 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /Blog/posts/delete/8
Stack Trace:
#0 [internal function]: PostsController->delete('8')
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 20:28:26 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /Blog/posts/delete/8
Stack Trace:
#0 [internal function]: PostsController->delete('8')
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 20:36:48 Error: [MissingControllerException] Controller class PostsaddController could not be found.
Exception Attributes: array (
  'class' => 'PostsaddController',
  'plugin' => NULL,
)
Request URL: /Blog/postsadd
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 21:54:34 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:54:34 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:55:01 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:55:01 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:55:46 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:55:46 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:56:59 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 15]
2016-03-05 21:56:59 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:57:29 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:57:29 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:57:33 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:57:33 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:58:24 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:58:24 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:58:42 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:58:42 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 21:59:27 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 21:59:27 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:03:18 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 22:03:18 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:03:36 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 22:03:36 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:04:55 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 14]
2016-03-05 22:04:55 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:06:00 Error: Fatal Error (1): Call to a member function save() on null in [C:\xampp\htdocs\Blog\app\Controller\ComentariosController.php, line 15]
2016-03-05 22:06:00 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /Blog/Comentarios/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:06:11 Error: [MissingActionException] Action ComentariosController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ComentariosController',
  'action' => 'index',
)
Request URL: /Blog/Comentarios
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ComentariosController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 22:07:00 Error: [MissingActionException] Action ComentariosController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ComentariosController',
  'action' => 'index',
)
Request URL: /Blog/Comentarios
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ComentariosController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 22:07:05 Error: [MissingActionException] Action ComentariosController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ComentariosController',
  'action' => 'index',
)
Request URL: /Blog/Comentarios
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ComentariosController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 22:09:29 Error: [MissingActionException] Action ComentariosController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ComentariosController',
  'action' => 'index',
)
Request URL: /Blog/Comentarios
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ComentariosController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 22:11:48 Error: [MissingActionException] Action ComentariosController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ComentariosController',
  'action' => 'index',
)
Request URL: /Blog/Comentarios
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ComentariosController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 22:14:07 Error: Fatal Error (4): syntax error, unexpected '$hasMany' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Blog\app\Model\Post.php, line 8]
2016-03-05 22:14:07 Error: [FatalErrorException] syntax error, unexpected '$hasMany' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /Blog/Posts/index/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 22:14:57 Error: Fatal Error (4): syntax error, unexpected '$hasMany' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Blog\app\Model\Post.php, line 8]
2016-03-05 22:14:57 Error: [FatalErrorException] syntax error, unexpected '$hasMany' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /Blog/Posts/index/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:06:14 Error: [MissingActionException] Action PostsController::categorias() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'categorias',
)
Request URL: /Blog/Posts/categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 23:06:24 Error: [MissingControllerException] Controller class CategoriasController could not be found.
Exception Attributes: array (
  'class' => 'CategoriasController',
  'plugin' => NULL,
)
Request URL: /Blog/categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 23:06:38 Error: [MissingControllerException] Controller class CategoriasController could not be found.
Exception Attributes: array (
  'class' => 'CategoriasController',
  'plugin' => NULL,
)
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 23:06:58 Error: [MissingActionException] Action CategoriasController::index() could not be found.
Exception Attributes: array (
  'controller' => 'CategoriasController',
  'action' => 'index',
)
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 23:07:36 Error: [MissingActionException] Action CategoriasController::index() could not be found.
Exception Attributes: array (
  'controller' => 'CategoriasController',
  'action' => 'index',
)
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 23:07:40 Error: [MissingActionException] Action CategoriasController::index() could not be found.
Exception Attributes: array (
  'controller' => 'CategoriasController',
  'action' => 'index',
)
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-05 23:07:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:07:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:08:01 Error: [MissingViewException] View file "Categorias\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'Categorias\\add.ctp',
)
Request URL: /Blog/Categorias/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 23:08:29 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:08:29 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:09:42 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:09:42 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:09:46 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:09:46 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:09:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:09:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:10:15 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:10:15 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:11:16 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:11:16 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:16 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:16 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:18 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:18 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:14:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriasController.php, line 13]
2016-03-05 23:14:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:24:27 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 40]
2016-03-05 23:24:27 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:24:42 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 40]
2016-03-05 23:24:42 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:24:47 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 40]
2016-03-05 23:24:47 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:24:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 40]
2016-03-05 23:24:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:24:54 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 40]
2016-03-05 23:24:54 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:25:33 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 41]
2016-03-05 23:25:33 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:25:34 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 41]
2016-03-05 23:25:34 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:25:40 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 41]
2016-03-05 23:25:40 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:25:54 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-05 23:25:54 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:27:18 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-05 23:27:18 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:27:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 53]
2016-03-05 23:27:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:28:04 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-05 23:28:04 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:28:09 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-05 23:28:09 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:28:13 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-05 23:28:13 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:30:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:30:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:31:59 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 53]
2016-03-05 23:31:59 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 53, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:32:10 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-05 23:32:10 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:32:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:32:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:05 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:05 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:06 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:06 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:06 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:06 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:33:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:33:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:11 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:11 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:13 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:13 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:15 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:15 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:22 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:22 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:24 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:24 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:27 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:27 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:29 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:29 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:31 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:31 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:34:35 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:34:35 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:35:27 Error: [MissingControllerException] Controller class CaController could not be found.
Exception Attributes: array (
  'class' => 'CaController',
  'plugin' => NULL,
)
Request URL: /Blog/ca
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-05 23:44:06 Error: [MissingViewException] View file "Categorias\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'Categorias\\add.ctp',
)
Request URL: /Blog/Categorias/add
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-05 23:51:59 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:51:59 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:52:53 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:52:53 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:53:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:53:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:53:31 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:53:31 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:53:32 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:53:32 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:53:39 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:53:39 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:53:43 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:53:43 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:54:22 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:54:22 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:54:25 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:54:25 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-05 23:57:59 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 51]
2016-03-05 23:57:59 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:00:53 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:00:53 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:03 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:03 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:04 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:04 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:48 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:48 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:02:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:02:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:15 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:15 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:40 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:40 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:42 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:42 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:43 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:43 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:43 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:43 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:44 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:44 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:44 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:44 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:44 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:44 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:44 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:44 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:45 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:45 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:45 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:45 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:45 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:45 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:04:45 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:04:45 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:05:02 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:05:02 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:06:12 Error: [NotFoundException] Postagem Inválida
Request URL: /Blog/Posts/edit/1
Stack Trace:
#0 [internal function]: PostsController->edit('1')
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 00:06:26 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:06:26 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:09:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:09:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:09:25 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 52]
2016-03-06 00:09:25 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:12:58 Error: Fatal Error (1): Call to a member function ready() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:12:58 Error: [FatalErrorException] Call to a member function ready() on null
Request URL: /Blog/posts/categoria
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:13:26 Error: Fatal Error (1): Call to a member function ready() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:13:26 Error: [FatalErrorException] Call to a member function ready() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:14:49 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:14:49 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:14:53 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:14:53 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:15:07 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:15:07 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:15:11 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:15:11 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:15:14 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:15:14 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:05 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:05 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:06 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:06 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:06 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:06 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:07 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:07 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:07 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:07 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:07 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:07 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:08 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:08 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:19:08 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 00:19:08 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:20:36 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:20:36 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:21:00 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:21:00 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:25:19 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:25:19 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:25:31 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriesController.php, line 14]
2016-03-06 00:25:31 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categories
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:26:16 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\CategoriesController.php, line 14]
2016-03-06 00:26:16 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/Categories
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:56:28 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:56:28 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:56:49 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:56:49 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:56:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:56:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 00:58:16 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 00:58:16 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:00:07 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 01:00:07 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:00:09 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 01:00:09 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:00:25 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 01:00:25 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:00:30 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 55]
2016-03-06 01:00:30 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /Blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:00:46 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:00:46 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:27 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:27 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:44 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:44 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:45 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:45 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:46 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:46 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:46 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:46 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:46 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:46 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:47 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:47 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:48 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:48 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:01:48 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:01:48 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:04:12 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 17]
2016-03-06 01:04:12 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:04:36 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 18]
2016-03-06 01:04:36 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:04:49 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 18]
2016-03-06 01:04:49 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:05:15 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 20]
2016-03-06 01:05:15 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:05:16 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 20]
2016-03-06 01:05:16 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:05:26 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 20]
2016-03-06 01:05:26 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:05:39 Error: Fatal Error (1): Call to a member function read() on null in [C:\xampp\htdocs\Blog\app\Controller\PostsController.php, line 19]
2016-03-06 01:05:39 Error: [FatalErrorException] Call to a member function read() on null
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:10:24 Error: [MissingActionException] Action PostsController::categoria() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'categoria',
)
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-06 01:10:38 Error: [MissingActionException] Action PostsController::categorias() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'categorias',
)
Request URL: /Blog/posts/categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-06 01:10:45 Error: [MissingActionException] Action PostsController::categoria() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'categoria',
)
Request URL: /Blog/posts/categoria/1
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-06 01:11:27 Error: [MissingViewException] View file "Categorias\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Categorias\\index.ctp',
)
Request URL: /Blog/Categorias
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(CategoriasController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 01:13:44 Error: [MissingControllerException] Controller class CategoriesController could not be found.
Exception Attributes: array (
  'class' => 'CategoriesController',
  'plugin' => NULL,
)
Request URL: /Blog/Categories
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 01:13:58 Error: [MissingControllerException] Controller class CategoriesController could not be found.
Exception Attributes: array (
  'class' => 'CategoriesController',
  'plugin' => NULL,
)
Request URL: /Blog/Categories
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 01:29:45 Error: Fatal Error (64): Cannot redeclare UsersController::beforeFilter() in [C:\xampp\htdocs\Blog\app\Controller\UsersController.php, line 73]
2016-03-06 01:29:45 Error: [FatalErrorException] Cannot redeclare UsersController::beforeFilter()
Request URL: /Blog/users/login
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 73)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 73, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 73, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:30:15 Error: Fatal Error (64): Cannot redeclare UsersController::beforeFilter() in [C:\xampp\htdocs\Blog\app\Controller\UsersController.php, line 87]
2016-03-06 01:30:15 Error: [FatalErrorException] Cannot redeclare UsersController::beforeFilter()
Request URL: /Blog/users/login
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 87)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 87, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 87, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 01:43:48 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 01:56:57 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /Blog/login
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 01:57:01 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /Blog/user
Stack Trace:
#0 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 01:57:03 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 02:15:58 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 02:19:05 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 02:19:37 Error: Fatal Error (1): Call to undefined function lr() in [C:\xampp\htdocs\Blog\app\Controller\UsersController.php, line 86]
2016-03-06 02:19:37 Error: [FatalErrorException] Call to undefined function lr()
Request URL: /Blog/users/login
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 86, Array)
#2 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 86, Array)
#3 C:\xampp\htdocs\Blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-06 13:39:54 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 13:42:10 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 13:45:36 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /Blog/users
Stack Trace:
#0 C:\xampp\htdocs\Blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-06 14:11:29 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /blog/Blog/
Stack Trace:
#0 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 14:11:31 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /blog/Blog/
Stack Trace:
#0 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 14:19:25 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /blog/Blog/
Stack Trace:
#0 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 14:20:27 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /blog/Blog/
Stack Trace:
#0 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 14:20:27 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /blog/Blog/
Stack Trace:
#0 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-03-06 14:21:39 Error: [MissingViewException] View file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\blog\lib\Cake\Controller\Controller.php(963): View->render(NULL, NULL)
#2 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-07 00:48:30 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\blog\app\Controller\PostsController.php, line 74]
2016-03-07 00:48:30 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /blog/posts/edit/14
Stack Trace:
#0 C:\xampp\htdocs\blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#3 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-07 00:48:35 Error: [NotFoundException] Invalid post
Request URL: /blog/posts/view
Stack Trace:
#0 [internal function]: PostsController->view()
#1 C:\xampp\htdocs\blog\lib\Cake\Controller\Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\blog\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 C:\xampp\htdocs\blog\app\webroot\index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-07 00:48:59 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\blog\app\Controller\PostsController.php, line 74]
2016-03-07 00:48:59 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#3 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-07 00:49:18 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\blog\app\Controller\PostsController.php, line 74]
2016-03-07 00:49:18 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /blog/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\blog\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#2 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 74, Array)
#3 C:\xampp\htdocs\blog\lib\Cake\Core\App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
